queue:
  name: Hosted Ubuntu 1604


variables:
  - group: 'Terraform Service Principal'
  - group: 'Terraform State'
  - name: tfstate_key
    value: 'jimpaine.terraform-azure-certs.master.tfstate'
  - name: resource_name
    value: 'certdemo'
  
steps:

- task: qetza.replacetokens.replacetokens-task.replacetokens@3
  displayName: 'Replace tokens in **/*.tfvars'

  inputs:
    rootDirectory: ./env
    targetFiles: '**/*.tfvars'

- script: |
   terraform init \
       -backend-config="resource_group_name=$(tfstate_resource_group)" \
       -backend-config="storage_account_name=$(tfstate_storage_account)" \
       -backend-config="container_name=$(tfstate_container)" \
       -backend-config="key=$(tfstate_key)" \
       -backend-config="access_key=$(tfstate_access_key)"

  workingDirectory: ./env
  displayName: 'Terraform init'

- script: |
   terraform apply -var-file=terraform.tfvars -auto-approve

  workingDirectory: ./env
  displayName: 'Terraform apply'